Repository Swifty9/Secure-U, pull requests merged in 2024-10, with the labels that each got.

#1 added the initial files
  .gitignore
  App.js
  app.json
  assets/adaptive-icon.png
  assets/announcement.png
  assets/attendance.png
  assets/breakfast.png
  assets/dinner.png
  assets/favicon.png
  assets/icon.png
  assets/lunch.png
  assets/menu.png
  assets/notification.png
  assets/profile-pic.png
  assets/profile.jpg
  assets/splash.png
  babel.config.js
  navigation/OwnerTabs.js
  navigation/StudentTabs.js
  package-lock.json
  package.json
  screens/LoginScreen.js
  screens/owners/AttendanceScreen.js
  screens/owners/DashboardScreen.js
  screens/owners/HomeScreen.js
  screens/owners/LoginScreen.js
  screens/owners/ProfileScreen.js
  screens/students/AttendanceScreen.js
  screens/students/DashboardScreen.js
  screens/students/HomeScreen.js
  screens/students/LoginScreen.js
  screens/students/NotificationsScreen.js
  screens/students/ProfileScreen.js
  yarn.lock
Labels: hacktoberfest, Hacktoberfest accepted

#2 changed owner name to Bodyguard
  screens/bodyguard/AttendanceScreen.js
  screens/bodyguard/DashboardScreen.js
  screens/bodyguard/HomeScreen.js
  screens/bodyguard/LoginScreen.js
  screens/bodyguard/ProfileScreen.js
Labels: bug, hacktoberfest, Hacktoberfest accepted

#4 added the initial code for student screen with basic level of sos imp…
  app.json
  package-lock.json
  package.json
  screens/students/HomeScreen.js
  yarn.lock
Labels: hacktoberfest, Hacktoberfest accepted

#5 added the whole working code this code is perfect and we can revert t…
  README.md
  app.json
  package-lock.json
  package.json
  screens/students/HomeScreen.js
  yarn.lock
Labels: hacktoberfest, Hacktoberfest accepted

#6 added working Student Screen V1
  screens/students/HomeScreen.js
Labels: hacktoberfest, Hacktoberfest accepted

#7 Updated the tab navigators
  App.js
  navigation/OwnerTabs.js
  navigation/StudentTabs.js
  package.json
  screens/students/HomeScreen.js
Labels: hacktoberfest, Hacktoberfest accepted

#8 added working forum page
  package.json
  screens/students/DashboardScreen.js
  yarn.lock
Labels: hacktoberfest, Hacktoberfest accepted

#11 Add profile screen for bodyguard
  screens/owners/ProfileScreen.js
Labels: hacktoberfest, Hacktoberfest accepted

#13 added the profile page and changes in home screen
  package.json
  screens/students/DashboardScreen.js
  screens/students/HomeScreen.js
  screens/students/ProfileScreen.js
  yarn.lock
Labels: hacktoberfest, Hacktoberfest accepted

#14 added safe area view for all the pages
  screens/owners/ProfileScreen.js
  screens/students/DashboardScreen.js
  screens/students/HomeScreen.js
  screens/students/ProfileScreen.js
Labels: good first issue, Hacktoberfest accepted

#16 added the new working code profile page which is properly working
  screens/owners/HomeScreen.js
  screens/students/DashboardScreen.js
  screens/students/ProfileScreen.js
Labels: hacktoberfest, Hacktoberfest accepted

#18 Solved Merge Conflicts
  screens/students/ProfileScreen.js
Labels: hacktoberfest, Hacktoberfest accepted

#19 added v1 login screen
  screens/LoginScreen.js
  screens/owners/HomeScreen.js
Labels: hacktoberfest, Hacktoberfest accepted

#21 added What'app UI for fake call button
  components/SOSScreen/FakeCallButton.js
Labels: hacktoberfest, Hacktoberfest accepted

#23 feat: Add Fake Call Image Customization in Settings
  App.js
  components/SOSScreen/FakeCallButton.js
  navigation/StudentStack.js
  package.json
  screens/students/FakeCallSettings.js
  screens/students/HomeScreen.js
  yarn.lock
Labels: hacktoberfest, Hacktoberfest accepted

#24 Change the required description
  screens/students/DashboardScreen.js
Labels: hacktoberfest, Hacktoberfest accepted

#25 feat: Add comment functionality with Supabase integration
  screens/students/DashboardScreen.js
  supabaseClient.js
Labels: hacktoberfest, Hacktoberfest accepted

#26 Update SecureU login screen UI for improved layout consistency and user experience.
  package.json
  screens/LoginScreen.js
  yarn.lock
Labels: hacktoberfest, Hacktoberfest accepted
